### PR TITLE
V3.0.0

### LINKED ISSUE #3: Allow to choose whether center circle or outer ones first
Hey, here is a new little need:
Here is what I need: image otherwise, the center circle is over the outer ones.

Change the order of these two lines according to a variable: 
image

### LINKED ISSUE #5: Children division offset
I don't know if it's a real issue or not (in case you can delete it):

image

startAngleDeg = 0
totalArchDeg = 180

What do you think ? We can see the offset here, maybe it's only usefull if the angle is set to 360 to not put 2 children over each other i don't know?

### PR DESCRIPTION
**Pull request by ahmednfwela**
* fixed wrong math equations
+ added separate class `CircularWidgetConfig` to hold the config
+ added `isAddExtraFakeItem` fixes #5
+ added  `drawOrder` fixes #3
* upgraded to flutter 3 and sdk 2.14.0

### CODE REVIEW

**Comment by baptistesx** [comment]
Sorry for the late delay, it works perfectly thanks! you can merge i guess? :)

**Comment by ahmednfwela** [comment]
Oh no problem, will publish now

**Comment by ahmednfwela** [comment]
@baptistesx v3.0.0 has been published to pub.dev

**Comment by baptistesx** [comment]
Awesome gg !

**Pull request merged**
